#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to serve "Hello World!" at the root
echo "Hello World!" > /usr/share/nginx/html/index.html

# Restart Nginx
kill -s HUP $(cat /var/run/nginx.pid) > /dev/null 2>&1 || true

